a = input("Enter Your Name: ")
b = input("Enter Your Class: ")
c = int(input("Enter Your Roll No: "))
d = input("Enter Your Batch: ")
print("Name:", a)
print("Class: ", b)
print("Roll No: ", c)
print("Batch", d)
print("------Updated File------")
